#
# @fileoverview GitHub Actions workflow for E2E tests
# @author Vibe Coding Demo
# @version 1.0.0
# @created 2024-01-15
# @modified 2024-01-15
#

name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Backend Dependencies
      run: |
        cd apps/backend
        npm ci
    
    - name: Install Frontend Dependencies
      run: |
        cd apps/frontend
        npm ci
    
    - name: Install E2E Dependencies
      run: |
        cd tests/e2e
        npm ci
    
    - name: Install Playwright Browsers
      run: |
        cd tests/e2e
        npx playwright install --with-deps
    
    - name: Setup Database
      run: |
        cd apps/backend
        npx prisma generate
        npx prisma db push
    
    - name: Start Backend
      run: |
        cd apps/backend
        npm run start:dev &
        sleep 10
    
    - name: Start Frontend
      run: |
        cd apps/frontend
        npm run build
        npm run preview &
        sleep 5
    
    - name: Run E2E Tests
      run: |
        cd tests/e2e
        npm test
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: tests/e2e/test-results/
        retention-days: 30
